### ISSUE TITLE
multiple last_called  devices with one account

### ISSUE THREAD

**Issue by h4nc** [keatontaylor/custom_components#97]
Coming from [here](https://community.home-assistant.io/t/echo-devices-alexa-as-media-player-testers-needed/58639/2017?u=h4nc)

> If you only have one Alexa account, then there should only be one last_called echo. There is a polling thread to determine the last serial number, and all devices will read an event when a new one is discovered and should adjust themselves. If you see more than one returning true (for more than a split second, which is the time for HA to tell every component), that’s a bug. Please file an issue.

I only have one account, but as noticed in another issue I have echo buttons in my network. 
For me it looked like they stay true (last_called) until I restart home assistant. 
I don't get an error.

To make it better readable I also extracted the last_called attributes to binary sensor and added them to my UI. This way I was better able to see if when the one gets TRUE if the other ons gets FALSE. But that did not happen. Both stayed TRUE.

In the thread above one other user seems to have the same issue, so I might not be the only one.
See: https://community.home-assistant.io/t/echo-devices-alexa-as-media-player-testers-needed/58639/2000?u=h4nc

**Comment by alandtse** [comment]
This is probably resolved with this [branch](https://github.com/alandtse/custom_components/tree/last_called_service) which also exposes the service to solve #83. Haven't tested it fully yet though.

**Comment by h4nc** [comment]
Unfortunately not. As you see in the attached pic, I can still have more than one entity last_called true (only one account).

sz_last is a device that also has echo buttons linked to it (which I use for routines).

Even calling the new service doesn't make it go false.

<img width="372" alt="1" src="https://user-images.githubusercontent.com/25117255/53493580-ef430700-3a9b-11e9-9143-2b196829fddd.png">

**Comment by h4nc** [comment]
I want to add that it still gets the right values when I restart home assistant

**Comment by alandtse** [comment]
Can you please try the latest version of the branch here and provide debugging logs for `custom_components.alexa_media.media_player` when you use the service. Specifically:

1. Use the service.
2. Speak to any Alexa device.
3. Use the service again.

I only need the logs covering these three steps.

**Comment by h4nc** [comment]
Ok so I added this to my configuration.yaml

```
logger:
  logs:
    custom_components.alexa_media: debug  
```

The logfile is really long. I couldn't find the logs covering these steps. 
Could you tell me how to to this? There is a lot going on in the logfile.

**Comment by alandtse** [comment]
You may need to turn off the other components if they're showing up.
```yaml
logger:
  default: info
  logs:
    custom_components.alexa_media: debug
```
When you use the service you should get something like this:
```
Feb 28 11:29:16 contrib-stretch hass[16148]: 2019-02-28 11:29:16 DEBUG (Thread-9) [custom_components.alexa_media] Service update_last_called for: []
Feb 28 11:29:17 contrib-stretch hass[16148]: 2019-02-28 11:29:17 DEBUG (Thread-9) [custom_components.alexa_media] a******e@gmail.com: Updated last_called: {'serialNumber': 'G************9WE', 'timestamp': 1551351265883}
```
You'll want to find the first time you see `Service update_last_called for: []` and copy between those two sections.

**Comment by h4nc** [comment]
I updated my post above with the log.

**Comment by alandtse** [comment]
Thanks. Echo Dot 3 is the only one reporting that it's the last called one. Is last_called true for the other dots?

**Comment by h4nc** [comment]
No currently not, because I restartet when I added logger.

Should I trigger another alexa to get more than one true and post again?

**Comment by alandtse** [comment]
Yes, as soon as you see the problem, please do the logging steps.

**Comment by h4nc** [comment]
Ok so now I have two last_called true again, logs:



```
2019-02-28 13:03:51 DEBUG (SyncWorker_1) [custom_components.alexa_media] ****@gmail.com: Found 7 devices, 1 bluetooth
2019-02-28 13:03:51 DEBUG (SyncWorker_1) [custom_components.alexa_media] ****@gmail.com: Existing: [<Entity Echo Dot 1: paused>, <Entity Echo Dot 2: standby>, <Entity Echo Dot 3: standby>] New: []; Filtered by: include_devices: ['Fire TV stick', 'Fire Tablet', 'This Device', "Alexa Apps"] exclude_devices:[]
2019-02-28 13:03:52 DEBUG (SyncWorker_1) [custom_components.alexa_media] ****@gmail.com: Updated last_called: {'serialNumber': 'G**************D', 'timestamp': 1551354908133}
2019-02-28 13:03:55 DEBUG (SyncWorker_15) [custom_components.alexa_media] Service update_last_called for: []
2019-02-28 13:03:55 DEBUG (SyncWorker_15) [custom_components.alexa_media] ****@gmail.com: Updated last_called: {'serialNumber': 'G**************D', 'timestamp': 1551354908133}

2019-02-28 13:06:59 DEBUG (SyncWorker_13) [custom_components.alexa_media] Service update_last_called for: []
2019-02-28 13:07:00 DEBUG (SyncWorker_13) [custom_components.alexa_media] ****@gmail.com: Updated last_called: {'serialNumber': 'G**************P', 'timestamp': 1551355613410}
2019-02-28 13:07:00 DEBUG (SyncWorker_13) [custom_components.alexa_media] ****@gmail.com: last_called changed: {'serialNumber': 'G**************D', 'timestamp': 1551354908133} to {'serialNumber': 'G**************P', 'timestamp': 1551355613410}
2019-02-28 13:07:00 DEBUG (SyncWorker_4) [custom_components.alexa_media.media_player] ****@gmail.com: Refreshing Echo Dot 1
2019-02-28 13:07:00 DEBUG (SyncWorker_7) [custom_components.alexa_media.media_player] Echo Dot 2 is last_called: G**************P
2019-02-28 13:07:00 DEBUG (SyncWorker_15) [custom_components.alexa_media.media_player] ****@gmail.com: Refreshing Echo Dot 3
2019-02-28 13:07:00 DEBUG (SyncWorker_7) [custom_components.alexa_media.media_player] ****@gmail.com: Refreshing Echo Dot 2
```

It also takes some seconds until the second one gets true. After some minutes the wrong one got false again. The logs seem to only report one alexa last called. So is this an ha issue?

<img width="364" alt="2" src="https://user-images.githubusercontent.com/25117255/53566498-9dae8100-3b5c-11e9-888b-3d9d464c309f.png">


And here you can see that both are true and just to be sure I show you the binarysensor config that reads that state also:

```
- platform: template
  sensors:
    wz_last: 
      value_template: "{{ states.media_player.echo_dot_1.attributes.last_called }}"
    
```

**Comment by alandtse** [comment]
I think I might have found the cause. Looks like we have to separately force HA to update.  I'm close to releasing a new release, so I didn't push it to the one you're testing yet. I'll let you know when we release it so you can confirm.

**Comment by h4nc** [comment]
Ok, I'd like to mention that I tried this in a script in the meantime. But that also did not help

```
    - service: homeassistant.update_entity
      data:
        entity_id: sensor.last_alexa  
```

**Comment by alandtse** [comment]
That's not the correct service if you're calling the last_called service.
```yaml
    - service: alexa_media.update_last_called
```

If you're referring to manually triggering the HA update, you'd have to do it to the media_players which are the source of you're binary_sensor (guessing at syntax for multiple entities).
```yaml
    - service: homeassistant.update_entity
      data:
        entity_id: media_player.echo_dot_1, media_player.echo_dot_2, media_player.echo_dot_3
```

**Comment by h4nc** [comment]
I tried this additionally to the alexa_media.update_last_called service.

But yes you are right, if I do this I have to update the meiaplayers. 
Should I try this or what for the new version?

**Comment by alandtse** [comment]
New version is out. It should resolve all the issues you referred to. After I confirm it's working in my production I'll make a post on the thread.

**Comment by h4nc** [comment]
Ok, I'd like to confirm that it works now, the last_called update instantly. Thanks!

I have another question about using delays, but I will ask that in the thread, because it will interessant more people.

Great work!
